sudo: false
branches:
  only:
  - master
language: ruby
rvm:
  - 2.2
install:
  - bundle install
before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/danielnaab/getitdunn.git"
  - git config --global user.email "dan@crushingpennies.com"
  - git config --global user.name "Travis-CI"
script:
  - bundle exec middleman prismic
  - bundle exec middleman build
  - bundle exec middleman deploy
env:
  global:
  - secure: "6J97S50/Ry4R+/PfxFwxrwOpZR5uAaiSi+QHQwPnsPpokJSvQpvochdQ96HOKhKkXBMdrYrm4RtCJCE20GhgZhRXm/gQHqZYetv9FZDugs+qNPABrj2iX0d+jo491FpgzsF8kGb7ZxvwTXGveh6+MEl0GDGCqkC23oACnX3qT1fYxfoc+3dMMZrCwhQJ+gWFThcCQD1sLC4H3yOHU6z2ucpthG63NOrnwRlu9xKcxQGPr+y3He6NZrYNHFzI+zLI2UtmOmRlJmM+YcmRN1jdJpJ5fN75vkOco4V8LB7dgybOevPBdFpxNnjsqW5FHy8A2CoSpVoYtqhG4n7j18l7ROynNjB/6XXC36KWYkzYE7ySC1pXdYrx37ZC0TKC8iKrgwHtWNLtbK81oOsRHCBnGlv6vsyFREutc3p5nKho+2aDOiniEgvhmW0sHbOB+OrIl8PvT+FRJb3y3rdYzRFL9Bu3QWfK2yW95ia6mY0CE4GYbDFWpz+Ju53aLx4JpUAmEaomRMcDNN/ID9VmG3tQj2qEJLKMh93QW03brl2jgozPe+cEcjpsYYdBV3rtgon6lJyXQM0+dU9zmgASjb/unopTAOt//ETJc4EJzqJQSI407rgkLKHqxQc5ZhXoWLVDxnu9LYdyl73ob/n+7InOHLh3JQ/RjuAbyLH5FjYQ6fg="
notifications:
  email:
    recipients:
      - danielnaab@gmail.com
    on_success: change
