version: "3.9"

services:
  app:
    build: .
    platform: linux/amd64
    volumes:
      - .:/src
      - ~/.ssh:/root/.ssh
    working_dir: /src
    ports:
      - "4567:4567"
    command: bundle exec middleman server
