name: Build getitdunnrun.com
on:
  workflow_dispatch:
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.2"
      - name: Build site
        run: |
          bundle exec middleman prismic
          bundle exec middleman build
          bundle exec middleman deploy
