name: Build getitdunnrun.com
on:
  workflow_dispatch:
  repository_dispatch:
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Build site
        run: docker-compose run middleman bundle exec middleman build
      - name: Deploy site
        run: docker-compose run middleman bundle exec middleman deploy
      - name: Build & Deploy to GitHub Pages
        with:
          REMOTE_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: yurikoval/middleman-gh-pages-action@master
