name: Build getitdunnrun.com
on:
  workflow_dispatch:
  repository_dispatch:
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Getting Prismic content
        run: docker-compose run middleman bundle exec middleman prismic
      - name: Build site
        run: docker-compose run middleman bundle exec middleman build
      - name: Deploy site
        run: ./deploy.sh
